ProjectGoGym/front-end

app/globals.css, app/layout-client.tsx, app/layout.tsx, app/page.tsx, components/Post/PostItem.tsx, components/Post/PostList.tsx, package-lock.json, package.json, post.json
- 게시판, 메인페이지에 재사용성이 좋은 게시물 컴포넌트 생성
- 페이지 테스트를 위한 json-server로 mockdata 생성
- api통신을 쉽게 처리하기 위한 tanstack-query 세팅
- **게시물 컴포넌트 카드형식 디자인**:
- **json-server 로 mock data 생성**:
- **tanstack-query 기본 세팅**:
- html, css 속성순서
- tanstack query 기본 세팅 방식
=> Design: PostItem / 게시물 컴포넌트 카드형식 디자인 및 mock data 생성, tanstack-query 기본 세팅

app/globals.css, app/layout.tsx, app/page.tsx, components/Footer.tsx, components/Post/PostList.tsx
- 메인 페이지 안에 푸터 디자인
- 메인 페이지 안에 푸터 디자인 기본 레이아웃
- **푸터 디자인**:
- **html, css 순서**
=> Design: footer

app/chat/page.tsx, app/community/[id]/page.tsx, app/globals.css, app/layout.tsx, app/mypage/page.tsx, components/Chat/Chat.tsx, components/Chat/ChatList.tsx, components/Chat/ChatRoom.tsx, components/MyProfile/ChangeProfile.tsx, components/MyProfile/GympayBox.tsx, components/Post/PostItem.tsx, components/UI/Nav.tsx, hooks/useTimeAgo.tsx, package-lock.json, package.json, post.json, store/useSocketStore.ts, tailwind.config.ts
- 채팅방, 채팅목록, 디자인 & 레이아웃 구현
- 채팅방, 채팅목록을 통해 실시간 통신을 위해
- **채팅방 디자인**:
- **채팅방 목록 디자인**:
- html, css순서
=> Design: 채팅방 페이지 & 채팅방 목록 & 대화상자

api/axiosInstance.ts, app/mypage/addGymPay/page.tsx, components/Chat/Chat.tsx, components/Chat/ChatRoom.tsx, components/MyProfile/ChargePay.tsx, components/MyProfile/GympayBox.tsx, components/Post/EditPost.tsx, components/Post/SearchKaKaoMap.tsx, package-lock.json, package.json, store/useSocketStore.ts
-  채팅기능 웹소켓 연결
-  포트원 api 연결
- zustand로 웹소켓 연결
- 백엔드 서버와 실시간 통신을 위한 웹소켓 연결
- 결제기능을 이용하기 위한 포트원 api 연결
- zustand로 웹소켓 연결기능을 추가해 재사용성 확장
- **마이페이지 안에 Gym pay 충전 기능 연결(백엔드와 연동x)**:
- **채팅메세지 수신,송신 기능 구현(백엔드와 연동x)**:
- 컴포넌트 효율성
- html,css 순서
=> feat: 채팅방 웹소켓 연결 & 포트원 api 연결

api/axiosInstance.ts, components/User/Login.tsx, components/User/Signup.tsx, next.config.ts, store/useLoginStore.ts
- 로그인 & 회원가입 백엔드 연동 / zustand 로그인 상태관리
- 로그인 상태관리
- **로그인 상태관리, api 프록시 구성,**:
=> feature: 로그인 & 회원가입 백엔드 연동 / zustand에 login 상태관리

app/mypage/changeProfile/page.tsx, app/mypage/page.tsx, components/MyProfile/ChangeProfile.tsx, components/MyProfile/Profile.tsx, components/Post/PostList.tsx, store/useLoginStore.ts
- 마이페이지 내 프로필 수정 기능
- 프로필 사진, 닉네임, 비밀번호, 핸드폰 번호 변경 할 수 있게 기능 구성
- **프로필 수정 페이지 **:
- 프로필 로직
-  html, css 순서,
=> Feat: 프로필 수정

app/mypage/page.tsx, components/UI/Nav.tsx
- 마이페이지 레이아웃
- 마이페이지 디자인 작업을 위해
- **마이페이지 작성할 내용 작성**
=> Design: 마이페이지 레이아웃

components/Chat/Chat.tsx, components/Chat/ChatRoom.tsx, components/UI/Nav.tsx, components/User/Signup.tsx, next.config.ts, store/useLoginStore.ts, store/useSocketStore.ts
- 채팅방 생성 기능 , 수신, 송신
- 1대1 실시간 채팅 구현
- **실시간 채팅**:
- **채팅방 디자인**:
=> feat: 채팅방 생성 & 수신 & 송신

app/globals.css, components/Chat/Chat.tsx, components/Chat/ChatRoom.tsx, components/MyProfile/ChargePay.tsx, components/MyProfile/MyPageNav.tsx, components/MyProfile/Profile.tsx, components/Post/Filter.tsx, components/Post/PostDetail.tsx, components/Post/PostItem.tsx, components/Post/PostListContainer.tsx, components/UI/DefaultProfile.tsx, components/UI/Nav.tsx, components/UI/Slider.tsx
- 버튼, 캐러셀, 게시판, 채팅메세지 UI 개선
-  Ui 개선
- **버튼, 프로필 이미지 아이콘 ui개선**:
=> Design: 네비게이션 바 & 버튼

components/User/Signup.tsx
✨ 변경 사항 (Changes)
- signup region 선택 재설정
=> Fix:Signup 관심지역 Region 재설정

components/Post/EditPost.tsx, components/Post/Filter.tsx, components/Post/PostDetail.tsx, components/Post/PostListContainer.tsx, constants/category.ts, next.config.ts, store/useLoginStore.ts
- 게시글 조회, 필터링, 작성하기, 상세보기 백엔드 연동 테스트
- 실제 서버와 연동 테스트
- **게시글 조회, 필터링, 작성하기, 상세보기**:
=> Feat: 게시글 백엔드연동

app/@modal/(.)community/[id]/imagedetail/page.tsx, app/@modal/(.)community/[id]/userdetail/page.tsx, app/@modal/default.tsx, app/community/[id]/imagedetail/page.tsx, app/community/[id]/userdetail/page.tsx, app/layout.tsx, components/Post/ModifiedPost.tsx, components/Post/PostDetail.tsx, components/Post/PostDetailImage.tsx, components/Post/PostDetailImageModal.tsx, components/Post/PostList.tsx, components/Post/PostListContainer.tsx, components/Post/PostUserDetail.tsx
- 모달을 paralell routes 과 interceopting routes을 이용해 구현
- 모달을 컴포넌트하나에서 state를 통해 조건부 렌더링을 하는것 보다 병렬처리 라우팅을 통해 페이지 렌더링 속도를 높일수 있고, 컴포넌트 안에 로직을 클린하게 작성할수있음
- **이미지 크게보기 모달, 회원의 다른 게시글 보기 모달 수정**
=> Fix: 게시글 상세보기 이미지 크게보기 모달

components/User/Signup.tsx
=> Fix:Region 수정

components/MyProfile/ChargePay.tsx, components/Post/ModifiedPost.tsx, components/Post/PostDetail.tsx, components/Post/PostItem.tsx, components/Post/PostList.tsx, components/Post/PostListContainer.tsx, next.config.ts
- 채팅방 백엔드 테스트 연동, 게시판 보내는 데이터 네이밍 수정
- websocket 연결 확인
- 수정하기, 작성하기 변수 네이밍 수정
- **websocket 연결**
- 수정하기, 작성하기 변수 네이밍 수정
=> Fix: 채팅방 백엔드 연동

components/Notification/Notice.tsx, components/UI/Nav.tsx, package-lock.json, package.json
=> Fix:Notification

components/Notification/Notice.tsx, components/UI/Nav.tsx, components/User/Login.tsx, components/User/Signup.tsx
- Notification 읽음상태 구현
- 알림 읽으면 ui에서 삭제
- 이용자가 알림을 확인하고 파악하기 위함
=> Feat:Notification Read

app/layout.tsx, app/page.tsx, components/Post/EditPost.tsx, components/Post/Filter.tsx, components/Post/ImageSelect.tsx, components/Post/PostList.tsx, components/Post/PostListContainer.tsx, components/SkeletonUI/PostItemSkeleton.tsx, components/UI/Footer.tsx, components/UI/MoblieMenu.tsx, components/UI/Nav.tsx, components/UI/Pagination.tsx, components/UI/Slider.tsx, package-lock.json, package.json, store/useUserStore.ts
- 게시물 컴포넌트 스켈레톤 처리, 메인페이지, 게시판 페이지, 게시글 작성페이지 반응형 디자인
- 데이터 로딩중 어떤 컨텐츠가 들어올지 짐작할수있게 해줌, 모바일,태블릿에서 사용이 가능하게 디자인
- **메인페이지, 게시판, 게시글 UI/UX개선**
=> Feat: 게시글 컴포넌트 스켈레톤 처리 & 메인페이지, 게시판 반응형 디자인 구현

app/globals.css, app/mypage/layout.tsx, app/mypage/page.tsx, app/test/page.tsx, components/Admin/ManageUserDetail.tsx, components/Chat/Chat.tsx, components/Chat/ChatPostDetail.tsx, components/Chat/ChatRoom.tsx, components/MyProfile/ChangeProfile.tsx, components/MyProfile/LookupPost.tsx, components/MyProfile/MyPageNav.tsx, components/MyProfile/Profile.tsx, components/Post/MainPagePostContainer.tsx, components/Post/ModifiedPost.tsx, components/Post/PostList.tsx, components/Post/PostListContainer.tsx, components/Post/PostUserDetail.tsx, components/UI/Nav.tsx, components/User/Login.tsx, next.config.ts, post.json
- 마이페이지 백엔드 테스트, 로직 수정, 안전결제 테스트
- 마이페이지의 유저정보를 받아오는 로직과 채팅에서 거래일정 잡기, 안전결제 테스트 실행
- **마이페이지 유저정보 받기, 프로필수정, 회원탈퇴하기**
- **안전결제 테스트**
=> Feat: 마이페이지 로직수정 & 마이페이지 백엔드 테스트 & 안전결제  테스트

components/Notification/Notice.tsx, components/UI/Nav.tsx, components/User/Login.tsx, components/User/Signup.tsx, next.config.ts
=> Feat:Profile URL

app/mypage/layout.tsx, app/mypage/page.tsx, app/mypage/postLook/[category]/page.tsx, components/Chat/Chat.tsx, components/Chat/ChatPostDetail.tsx, components/Chat/ChatRoom.tsx, components/MyProfile/ChangeProfile.tsx, components/MyProfile/GympayBox.tsx, components/MyProfile/LookupPost.tsx, components/MyProfile/MyPageNav.tsx, components/MyProfile/Profile.tsx, components/Post/EditPost.tsx, components/Post/ModifiedPost.tsx, components/Post/PostDetail.tsx, components/Post/PostItem.tsx, components/Post/PostList.tsx, components/Post/PostListContainer.tsx, components/Post/PostUserDetail.tsx, components/UI/Nav.tsx, components/UI/ProfileImage.tsx, components/UI/Slider.tsx, store/useLoginStore.ts, store/useSocketStore.ts, store/useUserStore.ts
- 채팅방 거래일정을 잡는 api와 상태값 설정,
- 게시글의 상태를 게시중, 거래중, 거래완료 등 상태를 변경하고 그에 맞게 api 전송
- 거래일정을 잡고 그에따른 알림을 보내주기 위함
- 게시글의 상태를 변경하고 거래중인지 거래가 완료되었는지를판단하기위함
=> Feat: 채팅방 로직 수정

components/Chat/Chat.tsx, components/Chat/Messages/ApproveMessages.tsx, components/Chat/Messages/NoticeMessages.tsx, components/Chat/Messages/RequestMessages.tsx, components/Chat/Messages/UserMessages.tsx, components/MyProfile/ChangeProfile.tsx, components/MyProfile/ChargePay.tsx, components/UI/Nav.tsx, components/User/Login.tsx, store/useLoginStore.ts
- 채팅 메세지 타입에 따른 메세지 업로드
- 알림과 유저 메세지를 구별하기 위함
=> Feat: 채팅 메세지 리팩토링

api/api.ts, api/axiosInstance.ts, components/Chat/Chat.tsx, components/Chat/ChatList.tsx, components/Chat/ChatPostDetail.tsx, components/Chat/ChatRoom.tsx, components/MyProfile/ChangeProfile.tsx, components/MyProfile/ChargePay.tsx, components/MyProfile/GympayBox.tsx, components/MyProfile/LookupPost.tsx, components/Notification/Notice.tsx, components/Post/EditPost.tsx, components/Post/ModifiedPost.tsx, components/Post/PostDetail.tsx, components/User/Login.tsx, components/User/Signup.tsx, next.config.ts, store/useSocketStore.ts
=> Fix: 배포 에러 수정

components/Chat/Chat.tsx, components/MyProfile/ChangeProfile.tsx
- 프로필 수정 & 웹소켓 연결부분 api 경로수정
- 배포서버와 개발서버가 다름
=> Fix: Chat api로직 수정 & 프로필 수정 로직 수정

components/Notice/Notice.tsx
=> Fix: SSE 수정 & 로그인, 회원가입 UI

components/Chat/Chat.tsx, components/Chat/ChatList.tsx, components/Chat/ChatPostDetail.tsx, components/Chat/Messages/RequestMessages.tsx, components/Notice/Notice.tsx, components/Post/MainPagePostContainer.tsx, components/Post/PostDetail.tsx, components/Post/PostItem.tsx, components/Post/PostList.tsx, components/Post/PostListContainer.tsx, components/User/Signup.tsx
- 채팅방 삭제시 리로드 되는 로직, 안전결제 요청 메세지에 문구 추가
- 채팅방 삭제시 데이터 최신화가 바로 되지않는 현상이 있어 리로드시킴,
- 안전결제 요청 메세지에 짐페이가 충분한지 확인하고 버튼을 누르게 유도
=> Feat: 채팅방 로직수정

components/Post/PostItem.tsx, components/Post/PostListContainer.tsx
- 게시물 데이터 로직 수정 page,size 전달시 ?을 안쓰고 &을 씀
=> Feat: 게시물 데이터 로딩 수정 & 레이아웃 수정

components/Post/PostDetail.tsx, components/Post/PostItem.tsx
- 작업내용: 게시글 삭제 버튼 추가 & 팝니다,삽니다 버튼 스타일 수정
=> Feat: 게시글 삭제버튼 추가 & postType 버튼 스타일

components/Post/PostDetail.tsx, components/Post/PostItem.tsx, components/Post/PostListContainer.tsx
작업내용: 게시글 삭제 버튼 추가 & 팝니다,삽니다 버튼 스타일 수정
=> Feat: 게시글 삭제버튼, 팝니다, 삽니다
